meta_product_name: "Coin Spread"
meta_title: "Coin Spread - Watch it, share it, spread it"
meta_description: "Stay ahead on th curve in the world of cryptocurrency"
meta_image: "resizedmetapic.png"                       # should exist in `app/assets/images/`
