meta_product_name: "CoinSpread"
meta_title: "CoinSpread - Read It, Share It, Spread It"
meta_description: "One Stop Shop for Crypto News, Prices, and Updates"
meta_image: "frontpage.png"                       # should exist in `app/assets/images/`
